export const API_ENDPOINTS = {
  GET_ALL_TIPY_POST: 'posts',

  GET_CAPTCHA: 'captcha',
  LOGIN_INVOICE: 'security-taxpayer/authenticate',
  SEARCH_INVOICE: 'query/invoices',
  SEARCH_INVOICE_PURCHASE: 'query/invoices/purchase',
  SEARCH_INVOICE_PURCHASE_SCO: 'sco-query/invoices/purchase',
  SEARCH_INVOICE_SOLD: 'query/invoices/sold',
  SEARCH_INVOICE_SOLD_SCO: 'sco-query/invoices/sold',
  GET_INVOICE_DETAIL: 'query/invoices/detail',
  GET_INVOICE_DETAIL_SCO: 'sco-query/invoices/detail',
  GET_INVOICE_EXPORT_XML: 'query/invoices/export-xml',
  GET_INVOICE_EXPORT_XML_SCO: 'sco-query/invoices/export-xml',
  GET_INVOICE_SOLD_EXPORT_EXCEL: 'query/invoices/export-excel-sold',
  GET_INVOICE_SOLD_EXPORT_EXCEL_SCO: 'sco-query/invoices/export-excel-sold',
  GET_INVOICE_PURCHASE_EXPORT_EXCEL: 'query/invoices/export-excel',
  GET_INVOICE_PURCHASE_EXPORT_EXCEL_SCO: 'sco-query/invoices/export-excel',

  USER_GET_ALL: "",
  USER_GET_ME: "users",
  USER_UPDATE_ME: "users",
  USER_LOGIN: "users/login",
  USER_LOGOUT: "users/logout",
  USER_SEND_VERIFY_CODE: "users/send-code-verify",
  USER_REFRESH_TOKEN: "",
  USER_REGISTER: "users/register",
  USER_RESET_PASSWORD: "users/reset-password",
  USER_VERIFY_CODE: "users/verify-code",
  USER_FORGOT_PASSWORD: "users/forgot-password",
};
