
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TanStackProvider from '@/provider/TanStackProvider';
//import { ReactQueryClientProvider } from '@/components/QueryClientProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Chuyên gia hoá đơn',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body className={inter.className}>
          <TanStackProvider>
            <div>{children}</div>
          </TanStackProvider>
        </body>
      </html>
  );
}
